version : '2.0.2'
services:
  # oner365-gateway
  oner365-gateway:
    container_name: oner365-gateway
    build:
      context: ./oner365-gateway
      dockerfile: dockerfile
    ports:
      - "8704:8704"
    volumes:
      - ./lib:/root/oner365-cloud/lib
    extra_hosts: 
      - "oner365-nacos:192.168.213.128"
    privileged: true
    restart: always

  # oner365-system
  oner365-system:
    container_name: oner365-system
    build:
      context: ./oner365-system
      dockerfile: dockerfile
    ports:
      - "8707:8707"
    volumes:
      - ./lib:/root/oner365-cloud/lib
    extra_hosts: 
      - "oner365-nacos:192.168.213.128"
    privileged: true
    restart: always

  # oner365-monitor
  oner365-monitor:
    container_name: oner365-monitor
    build:
      context: ./oner365-monitor
      dockerfile: dockerfile
    ports:
      - "8706:8706"
    volumes:
      - ./lib:/root/oner365-cloud/lib
    extra_hosts: 
      - "oner365-nacos:192.168.213.128"
    privileged: true
    restart: always