#部署目录
deploy:
  location: d:/gitee/oner365-cloud
  name: d:/gitee/deploy_nacos
  version: 1.0.0-SNAPSHOT
  suffix: jar
  project: oner365-elasticsearch,oner365-files,oner365-gateway,oner365-generator,oner365-hadoop,oner365-kafka,oner365-monitor,oner365-rocketmq,oner365-system
  lib: oner365-common,oner365-api

#服务器配置  
servers:
  deploy: false
  name: /home/oner365
  ip: 192.168.33.44
  port: 22
  username: root
  password: Ed30158d44