#部署目录
deploy:
  local:
    location: /Users/taoliu/gitee
    name: /Users/taoliu/gitee/deploy/nacos
    version: 2.0.2
    suffix: jar
    active: lt
    projects: 
      - oner365-websocket:8703
      - oner365-gateway:8704
      - oner365-files:8705
      - oner365-monitor:8706
      - oner365-system:8707
      - oner365-elasticsearch:8709
      - oner365-kafka:8710
      - oner365-generator:8711
      - oner365-hadoop:8712
      - oner365-rocketmq:8713
      - oner365-swagger:8714
      - oner365-pulsar:8715
      - oner365-datasource:8716
      - oner365-influx:8717
      - oner365-neo4j:8719
    libs: 
      - oner365-common
      - oner365-api
    
  server:
    deploy: false
    name: /home/oner365
    servers:
    - 192.168.33.44:22@root:Ed30158d44