#部署目录
deploy:
  local:
    location: /Users/zhaoyong/Documents/git/oner365-cloud
    name: /Users/zhaoyong/Documents/deploy/nacos
    version: 2.0.2
    suffix: jar
    active: zy
    projects: 
      - oner365-datasource
      - oner365-elasticsearch
      - oner365-files
      - oner365-gateway
      - oner365-generator
      - oner365-hadoop
      - oner365-influx
      - oner365-kafka
      - oner365-monitor
      - oner365-neo4j
      - oner365-pulsar
      - oner365-rocketmq
      - oner365-swagger
      - oner365-system
      - oner365-websocket
    libs: 
      - oner365-common
      - oner365-api
    
  server:
    deploy: false
    name: /home/oner365
    servers:
    - 192.168.33.44:22@root:Ed30158d44