#部署目录
deploy:
  local:
    location: /Users/taoliu/gitee
    name: /Users/taoliu/gitee/deploy/nacos
    version: 2.1.0
    suffix: jar
    active: lt
    server-addr: oner365-nacos:8848
    projects: 
      - oner365-websocket:8703
      - oner365-gateway:8704
      - oner365-files:8705
      - oner365-monitor:8706
      - oner365-system:8707
      - oner365-dubbo-provider:8708
      - oner365-elasticsearch:8709
      - oner365-kafka:8710
      - oner365-generator:8711
      - oner365-hadoop:8712
      - oner365-rocketmq:8713
      - oner365-swagger:8714
      - oner365-pulsar:8715
      - oner365-datasource:8716
      - oner365-influx:8717
      - oner365-dubbo-consumer:8718
      - oner365-neo4j:8719
      - oner365-cassandra:8720
      - oner365-statemachine:8721
      - oner365-vault:8722
      - oner365-mqtt:8723
      - oner365-ldap:8724
      - oner365-zookeeper:8725
      - oner365-spark:8726
      - oner365-mongodb:8727
      - oner365-kubernetes:8728
      - oner365-postgis:8729
      - oner365-shardingsphere:8730
      - oner365-clickhouse:8731
    libs: 
      - oner365-api
      - oner365-data-commons
      - oner365-data-datasource
      - oner365-data-jpa
      - oner365-data-redis
      - oner365-data-web
      - oner365-dubbo-api
    
  server:
    deploy: false
    name: /home/oner365
    servers:
    - 192.168.33.44:22@root:Ed30158d44