FROM jdk:1.8

LABEL com.oner365.image.authors="xiaozhao32@hotmail.com"

VOLUME /root/oner365-cloud/SERVICE_NAME
RUN mkdir -p /root/oner365-cloud/SERVICE_NAME
WORKDIR /root/oner365-cloud/SERVICE_NAME
#EXPOSE

ENV TZ=Asia/Shanghai
ENV PATH $PATH
ENV SPRING_PROFILES_ACTIVE=dev
ENV SPRING_CLOUD_NACOS_SERVER_ADDR=oner365-nacos:8848

ARG JAR_FILE
ARG OUT_DIRECTORY

COPY ${OUT_DIRECTORY}/lib /root/oner365-cloud/SERVICE_NAME/lib/
COPY ${OUT_DIRECTORY}/resources /root/oner365-cloud/SERVICE_NAME/resources/
COPY ${JAR_FILE} /root/oner365-cloud/SERVICE_NAME/SERVICE_NAME-SERVICE_VERSION.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", "-Dspring.cloud.nacos.server-addr=${SPRING_CLOUD_NACOS_SERVER_ADDR}", \
	"-jar", "/root/oner365-cloud/SERVICE_NAME/SERVICE_NAME-SERVICE_VERSION.jar"]

