version : '2.1.0'
services:
  # oner365-gateway
  oner365-gateway:
    container_name: oner365-gateway
    build:
      context: ./oner365-gateway
      dockerfile: dockerfile
    ports:
      - "8704:8704"
    volumes:
      - ./lib:/root/oner365-cloud/lib
    extra_hosts: 
      - "oner365-nacos:192.168.213.128"
    privileged: true
    restart: always

    