FROM jdk:1.8

LABEL com.oner365.image.authors="xiaozhao32@hotmail.com"

VOLUME /root/oner365-cloud/SERVICE_NAME
RUN mkdir -p /root/oner365-cloud/SERVICE_NAME
WORKDIR /root/oner365-cloud/SERVICE_NAME
#EXPOSE

ENV TZ=Asia/Shanghai
ENV PATH $PATH
ENV SPRING_PROFILES_ACTIVE=dev
ENV SPRING_CLOUD_NACOS_SERVER_ADDR=oner365-nacos:8848

COPY ./ /root/oner365-cloud/SERVICE_NAME/
ENTRYPOINT ["./start.sh"] 

