FROM jdk:11

VOLUME /root/oner365-cloud/oner365-gateway
RUN mkdir -p /root/oner365-cloud/oner365-gateway
WORKDIR /root/oner365-cloud/oner365-gateway
EXPOSE 8704

ENV TZ=Asia/Shanghai
ENV PATH $PATH

COPY ./ /root/oner365-cloud/oner365-gateway/
ENTRYPOINT ["./start.sh"] 

